apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-advanced
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/akuity/guestbook
      allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
      constraint: 0.0.1
  - git:
      repoURL: https://github.com/BenHesketh21/kargo-advanced.git
      branch: main
